#!/bin/bash

# -------------------------------------------------
# This script sssumes this is a git repository and
# that the last commit is merge commit.  If so,
# it extracts the merged branch name from the
# merge commit message.
# -------------------------------------------------

# Exit script on any errors
set -e

# Get the last commit message
merge_message=$(git log -1 --pretty=%B)

# Ensure it is the merge commit
if [[ "$merge_message" != *"Merge pull request #"* ]]; then
  echo ''
  exit 1
fi

# Extract the branch name
branch_name=$(echo $merge_message | awk -F '\\\\n' '{print $1}' |  awk -F '/' '{print $2}' | awk '{print $1}')
echo $branch_name
