name: Idempotent Build Push Image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      buildopts:
        type: string
    secrets:
      registry_u:
        required: true
      registry_p:
        required: true

jobs:

  pull-or-build-and-push-image:
    name: Pull or Build and Push Image
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.image }}

    steps:
      - uses: actions/checkout@v1

      - name: Image name
        run: echo "Image name [${IMAGE}]"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: If not pull image, build and push image
        env:
          DOCKER_BUILDKIT: 1
          BUILDOPTS: ${{ inputs.buildopts }}
        run: docker pull ${IMAGE} || (docker build --no-cache ${BUILDOPTS} -t ${IMAGE} . && docker push ${IMAGE})
      - name: Logout of DockerHub Registry
        run: docker logout
