name: Check Development Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1
  DEVENV: devenv
  APP_IMAGE: app-devenv

jobs:
  git-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Git log
        run: git log

  git-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  git-commit-sha:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Last commit of PR branch
        run: echo ${{ github.event.pull_request.head.sha }}

  git-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Branch
        run: echo ${{ github.head_ref }}

  build-devenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version

      - name: Build settings
        run: "echo DOCKER_BUILDKIT=${DOCKER_BUILDKIT} --target ${DEVENV} -t ${APP_IMAGE}"

      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${APP_IMAGE} ."

      - name: Check no mutation to source
        run: "[ ! -f foobear ]"

      - name: Mutate source in dev env
        run: docker run --rm -v ${PWD}:/app app-devenv touch foobear

      - name: Check source is mutated
        run: "[ -f foobear ]"

  run-tests-default:
    needs: build-devenv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${APP_IMAGE} ."

      - name: dockercomposerun (Run tests) with defaults (specify command)
        run: ./script/dockercomposerun bundle exec rake
