name: Development Environment Image

on:
  pull_request:
    branches:
      - main

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1
  DEVENV: devenv
  DEV_ENV_IMAGE: ${{ github.repository }}_${{ github.head_ref }}_dev:${{ github.event.pull_request.head.sha }}

jobs:
  devenv-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Dev environment image name
        run: echo "Dev Environment Image [${DEV_ENV_IMAGE}]"

  git-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Git log
        run: git log

  git-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  git-commit-sha:
    runs-on: ubuntu-latest

    steps:
      - name: Last commit of PR branch
        run: echo ${{ github.event.pull_request.head.sha }}

  git-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Branch
        run: echo ${{ github.head_ref }}

  build-devenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version

      - name: Build settings
        run: "echo DOCKER_BUILDKIT=${DOCKER_BUILDKIT} --target ${DEVENV} -t ${DEV_ENV_IMAGE}"

      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${DEV_ENV_IMAGE} ."

      - name: Check no mutation to source
        run: "[ ! -f foobear ]"

      - name: Mutate source in dev env
        run: docker run --rm -v ${PWD}:/app ${DEV_ENV_IMAGE} touch foobear

      - name: Check source is mutated
        run: "[ -f foobear ]"

  set-tag-output-from-commit-sha:
    runs-on: ubuntu-latest
    outputs:
      src-tag: ${{ steps.tag.outputs.commitsha }}

    steps:
      - uses: actions/checkout@v1
      - name: Set tag
        id: tag
        run: echo "::set-output name=commitsha::$(git log -n 1 --skip 1 --pretty=format:"%H")"

  output-set-tag:
    needs: [set-tag-output-from-commit-sha]
    runs-on: ubuntu-latest

    steps:
      - name: Output tag in later job
        run: echo "The src tag = [${{ needs.set-tag-output-from-commit-sha.outputs.src-tag }}]"
