name: Display Basic Git and GitHub (Actions) Info

on:
  workflow_call:

jobs:
  git-github-info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Git log
        run: git log

      - name: Last git commit (SHA)
        run: echo "$(git log -1 --format="%H" | grep -v -e '^$')"

      - name: Last git commit message
        run: echo "$(git log -1 --format="%B" | grep -v -e '^$')"

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
