name: On Merge Promote Branch Image to Prod
on:
  push:
    branches:
      - main

jobs:

  # merged-branch-last-commit:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     branch-commit: ${{ steps.getcommit.outputs.lastcommit }}

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Get last commit of merged branch
  #       id: getcommit
  #       run: echo "::set-output name=lastcommit::$(git log -n 1 --skip 1 --pretty=format:"%H")"

  # merged-branch-name:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     branch-name: ${{ steps.getbranch.outputs.branchname }}

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Get merged branch name from merge commit message
  #       id: getbranch
  #       run: echo "::set-output name=branchname::$(./.github/scripts/branch-name-from-merge-msg)"

  branch-and-last-commit:
    uses: brianjbayer/gh-actions-test-bed/.github/workflows/get-merged-branch-last-commit.yml@9b903d417332a3baa13e828861c4ec6b4c7c9436

  branch-and-last-commit-merged-info:
    needs: [branch-and-last-commit]
    runs-on: ubuntu-latest
    env:
      BRANCH_LAST_COMMIT: ${{ needs.branch-and-last-commit.outputs.commit }}
      BRANCH: ${{ needs.branch-and-last-commit.outputs.branch }}

    steps:
      - name: Output last commit of merged branch env var
        run: echo "BRANCH_LAST_COMMIT=[${BRANCH_LAST_COMMIT}]"

      - name: Output last commit of merged branch raw
        run: echo "BRANCH LAST COMMIT is [${{ needs.branch-and-last-commit.outputs.commit }}]"

      - name: Output merged branch env var
        run: echo "BRANCH=[${BRANCH}]"

      - name: Output merged branch raw
        run: echo "BRANCH=[${BRANCH}]"

  promote-branch-last-commit-to-prod:
    needs: [branch-and-last-commit]
    uses: brianjbayer/gh-actions-test-bed/.github/workflows/pull-push-image.yml@9b903d417332a3baa13e828861c4ec6b4c7c9436
    with:
      # Pull last vetted branch image
      pull_as: ${{ github.repository }}_${{ needs.branch-and-last-commit.outputs.branch }}:${{ needs.branch-and-last-commit.outputs.commit }}
      # Push prod Image
      push_as: ${{ github.repository }}:${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # runs-on: ubuntu-latest
    # env:
    #   env:
    #   GIT_REPO: ${{ github.repository }}
    #   BRANCH_LAST_COMMIT: ${{ needs.merged-branch-last-commit.outputs.branch-commit }}
    #   BRANCH: ${{ needs.merged-branch-name.outputs.branch-name }}

    # steps:
    #   - uses: actions/checkout@v1

    #   - name: Merged branch
    #     run: echo "BRANCH= [${BRANCH}]"

    #   - name: Last commit of Merged branch
    #     run: echo "BRANCH_LAST_COMMIT= [${BRANCH_LAST_COMMIT}]"

    #   - name: Merged branch last commit vetted deploy image name
    #     run: echo "Pulling image [${GIT_REPO}_${BRANCH}:${BRANCH_LAST_COMMIT}]"

    #   - name: Prod commit-tagged image name
    #     run: echo "Pushing image [${GIT_REPO}:${BRANCH_LAST_COMMIT}]"

    #   - name: Login to DockerHub Registry
    #     run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    #   - name: Pull Merged branch last commit vetted deploy image and Push to commit-tagged Prod
    #     run: ./.github/scripts/docker-pull-push ${GIT_REPO}_${BRANCH}:${BRANCH_LAST_COMMIT} ${GIT_REPO}:${BRANCH_LAST_COMMIT}

    #   - name: Pull Merged branch last commit vetted deploy image and Push to Prod latest
    #     run: ./.github/scripts/docker-pull-push -f ${GIT_REPO}_${BRANCH}:${BRANCH_LAST_COMMIT} ${GIT_REPO}:latest

    #   - name: Logout of DockerHub Registry
    #     run: docker logout

  promote-branch-last-commit-to-prod-latest:
    needs: [branch-and-last-commit, promote-branch-last-commit-to-prod]
    uses: brianjbayer/gh-actions-test-bed/.github/workflows/pull-push-latest-image.yml@9b903d417332a3baa13e828861c4ec6b4c7c9436
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  promote-branch-last-commit-devenv:
    needs: [branch-and-last-commit]
    uses: brianjbayer/gh-actions-test-bed/.github/workflows/pull-push-image.yml@9b903d417332a3baa13e828861c4ec6b4c7c9436
    with:
      # Pull last branch devenv image
      pull_as: ${{ github.repository }}_${{ needs.branch-and-last-commit.outputs.branch }}_dev:${{ needs.branch-and-last-commit.outputs.commit }}
      # Push prod devenv image
      push_as: ${{ github.repository }}-dev:${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # needs: [merged-branch-last-commit, merged-branch-name]
    # runs-on: ubuntu-latest
    # env:
    #   env:
    #   GIT_REPO: ${{ github.repository }}
    #   BRANCH_LAST_COMMIT: ${{ needs.merged-branch-last-commit.outputs.branch-commit }}
    #   BRANCH: ${{ needs.merged-branch-name.outputs.branch-name }}

    # steps:
    #   - uses: actions/checkout@v1

    #   - name: Merged branch
    #     run: echo "BRANCH= [${BRANCH}]"

    #   - name: Last commit of Merged branch
    #     run: echo "BRANCH_LAST_COMMIT= [${BRANCH_LAST_COMMIT}]"

    #   - name: Merged branch last commit dev environment image name
    #     run: echo "Pulling image [${GIT_REPO}_${BRANCH}_dev:${BRANCH_LAST_COMMIT}]"

    #   - name: Devenv commit-tagged image name
    #     run: echo "Pushing image [${GIT_REPO}-dev:${BRANCH_LAST_COMMIT}]"

    #   - name: Login to DockerHub Registry
    #     run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    #   - name: Pull Merged branch last commit dev environment image and Push to commit-tagged dev environment
    #     run: ./.github/scripts/docker-pull-push ${GIT_REPO}_${BRANCH}_dev:${BRANCH_LAST_COMMIT} ${GIT_REPO}-dev:${BRANCH_LAST_COMMIT}

    #   - name: Pull Merged branch last commit dev environment image and Push to dev environment latest
    #     run: ./.github/scripts/docker-pull-push -f ${GIT_REPO}_${BRANCH}_dev:${BRANCH_LAST_COMMIT} ${GIT_REPO}-dev:latest

    #   - name: Logout of DockerHub Registry
    #     run: docker logout

  promote-branch-last-commit-devenv-to-latest:
    needs: [branch-and-last-commit, promote-branch-last-commit-devenv]
    uses: brianjbayer/gh-actions-test-bed/.github/workflows/pull-push-latest-image.yml@9b903d417332a3baa13e828861c4ec6b4c7c9436
    with:
      image_name: ${{ github.repository }}-dev
      image_tag: ${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
