name: Pull Image and Push As Latest

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      registry_u:
        required: true
      registry_p:
        required: true

jobs:

  pull-image-tag-push-image-latest:
    name: Pull Image:Tag Push Image:latest
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ inputs.image_name }}
      IMAGE_TAG: ${{ inputs.image_tag }}
      LATEST_TAG: latest

    steps:
      - name: Pull as image name and tag
        run: echo "Pull as image name [${IMAGE_NAME}:${IMAGE_TAG}]"

      - name: Push as image name latest
        run: echo "Push as image name [${IMAGE_NAME}:${LATEST_TAG}]"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: Pull Image Tag
        run: docker pull ${IMAGE_NAME}:${IMAGE_TAG}

      - name: Tag Image as latest
        run: docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${LATEST_TAG}

      - name: Push Image latest
        run: docker push ${IMAGE_NAME}:${LATEST_TAG}

      - name: Logout of DockerHub Registry
        run: docker logout
