name: Idempotent Pull As Image Push As Image

on:
  workflow_call:
    inputs:
      pull_as:
        required: true
        type: string
      push_as:
        required: true
        type: string
    secrets:
      registry_u:
        required: true
      registry_p:
        required: true

jobs:

  pull-or-pull-and-push-images:
    name: Pull or Pull and Push Images
    runs-on: ubuntu-latest
    env:
      PULL_AS: ${{ inputs.pull_as }}
      PUSH_AS: ${{ inputs.push_as }}

    steps:
      - name: Pull as image name
        run: echo "Pull as image name [${PULL_AS}]"

      - name: Push as image name
        run: echo "Push as image name [${PUSH_AS}]"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: If not pull push-as image, pull and push image
        run: docker pull ${PUSH_AS} || (docker pull ${PULL_AS} && docker tag ${PULL_AS} ${PUSH_AS} && docker push ${PUSH_AS})

      - name: Logout of DockerHub Registry
        run: docker logout
