name: Push to Main

on:
  push:
    branches:
      - main

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1
  DEVENV: devenv
  DEV_ENV_IMAGE: ${{ github.repository }}_${{ github.head_ref }}_dev:${{ github.event.pull_request.head.sha }}

jobs:

  git-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Git log
        run: git log

  git-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  git-commit-sha:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Last commit of PR branch
        run: echo ${{ github.event.head_commit.id }}

  git-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Branch
        run: echo ${{ github.head_ref }}
