name: Push to Main

on:
  push:
    branches:
      - main

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1

jobs:
  git-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Git log
        run: git log

  git-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  git-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Last commit of PR branch
        run: echo "Message is... [${{ github.event.head_commit.message }}]"

  merged-branch-last-commit:
    runs-on: ubuntu-latest
    outputs:
      branch-commit: ${{ steps.getcommit.outputs.lastcommit }}

    steps:
      - uses: actions/checkout@v1
      - name: Get last commit of merged branch
        id: getcommit
        run: echo "::set-output name=lastcommit::$(git log -n 1 --skip 1 --pretty=format:"%H")"

  output-set-tag:
    needs: [merged-branch-last-commit]
    runs-on: ubuntu-latest
    env:
      SRC_TAG: ${{ needs.merged-branch-last-commit.outputs.branch-commit }}

    steps:
      - name: Output tag in later job
        run: echo "The src tag = [${{ needs.merged-branch-last-commit.outputs.branch-commit }}]"

      - name: Output tag in later job as env var
        run: echo "SRC_TAG= [${SRC_TAG}]"

