name: Run the Command with Image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:

  run-command-with-image:
    name: Run the Command with the image
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.image }}
      COMMAND: ${{ inputs.command }}

    steps:
      - uses: actions/checkout@v1
      - name: Display image name
        run: echo "Image is [${IMAGE}]"

      - name: Display command
        run: echo "Command is [${COMMAND}]"

      - name: Run command
        run: "${COMMAND}"
