name: Vet That Image Can Be Modified
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  vet-image-mutable:
    name: Verify that image can be modified
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.image }}

    steps:
      - name: Pull image
        run: docker pull ${IMAGE}

      - name: Check originally no mutation to local
        run: "[ ! -f foobear ]"

      - name: Run and mount source and mutate in the container
        run: docker run --rm -v ${PWD}:/app ${IMAGE} touch foobear

      - name: Check local is mutated after image exit
        run: "[ -f foobear ]"
